apiVersion: v1
kind: PersistentVolume
metadata:
  name: osm3s-dbdir-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/osm3s-db-vol/"